name: Nath CD
run-name: deploying project with infra

on:
  workflow_dispatch:
    repository_dispatch:
      types: [deploy_project]
    push:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: A event received
        run: |
          echo "payload Foo '${{ github.event.client_payload.foo }}' '${{ github.event.branch }}'"
          
