name: Nath CD
run-name: deploying project with infra

on:
  repository_dispatch:
    types: [deploy_project]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.branch == 'main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          # Optional, directory where playbooks live
          directory: ./provisioning
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory environments/prod

